<?php

namespace Database\Seeders;

use App\Models\SpmbStep;
use Illuminate\Database\Seeder;

class SpmbStepSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $steps = [
            [
                'title'       => 'Pendaftaran Akun',
                'slug'        => 'pendaftaran-akun',
                'description' => 'Membuat akun pendaftaran menggunakan Email aktif dan melakukan aktivasi melalui email, atau dapat melakukan login dengan Google',
                'period_text' => '01 Mei - 24 Juni 2026',
                'start_date'  => '2026-05-01 00:00:00',
                'end_date'    => '2026-06-24 15:00:00',
                'step_order'  => 1,
                'icon'        => 'fa-user-plus',
                'color'       => 'cyan',
                'tags'               => json_encode(['Email Aktif', 'Verifikasi Email']),
                'note'               => null,
                'alert_text'         => null,
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
            [
                'title'       => 'Pengisian Biodata',
                'slug'        => 'pengisian-biodata',
                'description' => 'Melengkapi data diri, asal sekolah, data orang tua/wali, serta mengunggah pasfoto resmi.',
                'period_text' => '01 Mei - 24 Juni 2026',
                'start_date'  => '2026-05-01 00:00:00',
                'end_date'    => '2026-06-24 15:00:00',
                'step_order'  => 2,
                'icon'        => 'fa-id-card',
                'color'       => 'blue',
                'tags'               => json_encode(['Data Pribadi', 'Alamat', 'Asal Sekolah', 'Data Ortu', 'Pas Foto']),
                'note'               => null,
                'alert_text'         => null,
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
            [
                'title'       => 'Pendaftaran SPMB',
                'slug'        => 'pendaftaran-spmb',
                'description' => 'Kunci biodata (finalisasi) dan pilih jalur pendaftaran, konsentrasi keahlian/jurusan pendaftaran.',
                'period_text' => '02 Juni - 24 Juni 2026',
                'start_date'  => '2026-06-02 00:00:00',
                'end_date'    => '2026-06-24 15:00:00',
                'step_order'  => 3,
                'icon'        => 'fa-id-card',
                'color'       => 'purple',
                'tags'               => json_encode(['Info Kuota', 'Pilihan Konsentrasi Keahlian']),
                'note'               => null,
                'alert_text'         => null,
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 1,
            ],
            [
                'title'       => 'Verifikasi Dokumen',
                'slug'        => 'verifikasi-dokumen',
                'description' => 'Proses pengecekan dan validasi berkas pendaftaran oleh tim panitia seleksi SPMB.',
                'period_text' => '02 Juni - 24 Juni 2026',
                'start_date'  => '2026-06-02 00:00:00',
                'end_date'    => '2026-06-24 15:00:00',
                'step_order'  => 4,
                'icon'        => 'fa-file-shield',
                'color'       => 'purple',
                'tags'               => json_encode(['Ijazah', 'Surat Keterangan Lulus', 'Rapor', 'Pas Foto', 'Surat keterangan rata-rata nilai Rapor']),
                'note'               => null,
                'alert_text'         => 'Peserta hadir melakukan verifikasi berkas dan observasi untuk seleksi minat dan bakat.',
                'show_statuses'      => 1,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
            [
                'title'       => 'Seleksi Akademik',
                'slug'        => 'seleksi-akademik',
                'description' => 'Pelaksanaan Observasi seleksi minat dan bakat untuk mengukur kemampuan akademik.',
                'period_text' => '02 - 24 Juni 2026',
                'start_date'  => '2026-06-02 00:00:00',
                'end_date'    => '2026-06-24 15:00:00',
                'step_order'  => 5,
                'icon'        => 'fa-laptop-code',
                'color'       => 'amber',
                'tags'               => json_encode(['Observasi', 'Minat dan Bakat']),
                'note'               => null,
                'alert_text'         => 'Jadwal Seleksi: 23 - 24 Juni 2026',
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
            [
                'title'       => 'Pengumuman Hasil',
                'slug'        => 'pengumuman-hasil',
                'description' => 'Melihat hasil penjenjangan kelulusan akhir langsung melalui halaman dashboard akun Anda.',
                'period_text' => '25 Juni 2026',
                'start_date'  => '2026-06-25 12:00:00',
                'end_date'    => '2026-06-25 23:59:59',
                'step_order'  => 6,
                'icon'        => 'fa-bullhorn',
                'color'       => 'emerald',
                'tags'               => null,
                'note'               => null,
                'alert_text'         => 'Jadwal Pengumuman: 25 Juni 2026',
                'show_statuses'      => 0,
                'show_result_badges' => 1,
                'is_highlight'       => 1,
            ],
            [
                'title'       => 'Daftar Ulang & Penyerahan Berkas',
                'slug'        => 'daftar-ulang-dan-penyerahan-berkas',
                'description' => 'Proses registrasi ulang secara sistem dan penyerahan dokumen fisik persyaratan ke kampus.',
                'period_text' => '26 - 27 Juni 2026',
                'start_date'  => '2026-06-26 00:00:00',
                'end_date'    => '2026-06-27 16:00:00',
                'step_order'  => 7,
                'icon'        => 'fa-user-check',
                'color'       => 'indigo',
                'tags'               => json_encode(['Konfirmasi Hadir', 'Penyerahan Berkas']),
                'note'               => null,
                'alert_text'         => null,
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
            [
                'title'       => 'Masa Pengenalan Lingkungan Sekolah',
                'slug'        => 'masa-pengenalan-lingkungan-sekolah',
                'description' => 'Kegiatan pengenalan lingkungan sekolah, program akademis, tata tertib, dan budaya sekolah.',
                'period_text' => '13 - 14 Juli 2026',
                'start_date'  => '2026-07-13 00:00:00',
                'end_date'    => '2026-07-14 23:59:59',
                'step_order'  => 8,
                'icon'        => 'fa-users-gear',
                'color'       => 'teal',
                'tags'               => json_encode(['MPLS']),
                'note'               => null,
                'alert_text'         => null,
                'show_statuses'      => 0,
                'show_result_badges' => 0,
                'is_highlight'       => 0,
            ],
        ];

        foreach ($steps as $step) {
            SpmbStep::create($step);
        }
    }
}
